const dataManager = {
    originalTileJs: null,

    openSmart() { document.getElementById('file-loader').click(); },

    onFileSelected(input) {
        const file = input.files[0];
        if (!file) return;
        const reader = new FileReader();
        reader.onload = (e) => this.parseData(e.target.result);
        reader.readAsText(file);
    },

    onTileJsSelected(input) {
        const file = input.files[0];
        if (!file) return;
        const reader = new FileReader();
        reader.onload = (e) => {
            this.originalTileJs = e.target.result;
            document.getElementById('tile-js-status').style.display = 'none';
            alert("tile.js loaded. You can now save patched versions.");
        };
        reader.readAsText(file);
    },

    openImport() { document.getElementById('json-modal').style.display = 'block'; },

    processImport() {
        this.parseData(document.getElementById('json-io').value);
        document.getElementById('json-modal').style.display = 'none';
    },

    parseData(txt) {
        try {
            let jsonStr = txt;
            if (txt.includes("WORLD_LAYOUTS =")) {
                const start = txt.indexOf("{", txt.indexOf("WORLD_LAYOUTS"));
                let count = 0;
                for (let i = start; i < txt.length; i++) {
                    if (txt[i] === '{') count++;
                    if (txt[i] === '}') count--;
                    if (count === 0 && i > start) {
                        jsonStr = txt.substring(start, i + 1);
                        break;
                    }
                }
            }

            const strictJson = jsonStr.replace(/([a-zA-Z0-9_-]+):/g, '"$1":').replace(/'/g, '"');
            const data = JSON.parse(strictJson);

            const newData = {};
            for (let key in data) {
                newData[key] = data[key].map(rowStr => {
                    if (Array.isArray(rowStr)) return rowStr;
                    return rowStr.split('').map(char => {
                        return getTileValue(char);
                    });
                });
            }

            worldData = newData;
            app.renderPalette();
            app.selectRoom(0, 0);
            alert("Map Loaded!");

        } catch (e) {
            console.error(e);
            alert("Parse error. Check console.");
        }
    },

    saveWithUI() {
        const status = document.getElementById('tile-js-status');
        if (!this.originalTileJs) {
            status.style.display = 'block';
            status.innerText = "Warning: tile.js not loaded. Cannot patch tile definitions.";
        } else {
            status.style.display = 'none';
        }
        document.getElementById('save-modal').style.display = 'flex';
    },

    saveMap() {
        document.getElementById('save-modal').style.display = 'none';

        let content = `// Generated by BOSS Editor\n`;
        content += `const WORLD_LAYOUTS = {\n`;

        const keys = Object.keys(worldData).sort((a, b) => {
            const [ax, ay] = a.split(',').map(Number);
            const [bx, by] = b.split(',').map(Number);
            return ay === by ? ax - bx : ay - by;
        });

        keys.forEach((key, i) => {
            content += `    "${key}": [\n`;
            worldData[key].forEach((row, ri) => {
                const rowStr = row.map(id => {
                    // BUG FIX: Prioritize the exportChar defined in TILE_DEF
                    if (TILE_DEF[id] && TILE_DEF[id].exportChar) {
                        return TILE_DEF[id].exportChar;
                    }
                    // Fallback to searching the map
                    const entry = Object.entries(TILE_DATA_MAP).find(([k, v]) => v === id && k.length === 1);
                    return entry ? entry[0] : (id === 0 ? '0' : '?');
                }).join('');
                content += `        "${rowStr}"${ri < 17 ? ',' : ''}\n`;
            });
            content += `    ]${i < keys.length - 1 ? ',' : ''}\n`;
        });
        content += `};\n`;

        this.download(content, 'rooms.js');
    },

    savePatchedTileJs() {
        if (!this.originalTileJs) {
            alert("Please load the original tile.js first using the 'LOAD TILE.JS' button.");
            return;
        }

        let content = this.originalTileJs;

        // Iterate through all new tiles created in this session
        NEW_TILES_LIST.forEach(tile => {
            // 1. Inject into TILE_DATA_MAP
            // Strategy: Find "const TILE_DATA_MAP = {" ... find the first "};" after that.
            const mapStart = content.indexOf("const TILE_DATA_MAP = {");
            if (mapStart !== -1) {
                const mapEnd = content.indexOf("};", mapStart);
                if (mapEnd !== -1) {
                    const injection = `    '${tile.char}': ${tile.id},\n`;
                    content = content.slice(0, mapEnd) + injection + content.slice(mapEnd);
                }
            }

            // 2. Inject into TILE_DEF
            // Strategy: Find "const TILE_DEF = {" ... find the first "};" after that.
            // Note: TILE_DEF contains objects, so we must match braces carefully or just use the structure provided
            // The provided tile.js ends TILE_DEF with "};" at the root level.
            // A simple hack is to find the LAST occurrence of "};" inside the file context if we assume structure
            // BUT safer: Find "const TILE_DEF" then regex search for the closing brace. 
            // Given the known format, we look for the line starting with "};" after TILE_DEF

            // However, since we are appending lines inside the block, simply finding the last "};" relative to TILE_DEF start is risky if code follows.
            // Let's rely on the specific indentation pattern or just the end of file? No.

            // Let's assume standard formatting from the provided file: "};" closes the block.
            // We search for `const TILE_DEF = {`
            // Then we search for `^};` (multiline) or just insert before the LAST `};` found if we assume it's near end of definitions section.

            // More Robust: Find "const TILE_DEF", count braces? Too complex for this snippet.
            // Simple approach: Look for "99: { name: "Spike", ... }" or the last known key? 
            // Better: Insert at the end of the TILE_DEF block.
            // We'll search for "const TILE_DEF = {" and then the next "};" that appears at the start of a line.
            const defStart = content.indexOf("const TILE_DEF = {");
            if (defStart !== -1) {
                // Find closing brace. It usually follows the last definition.
                // We'll insert before the `};` that closes TILE_DEF.
                // Because we modified content in step 1, indices shifted. Re-search.
                let ptr = defStart;
                let braceCount = 0;
                let foundStart = false;
                let closingIndex = -1;

                // Simple parser to find matching brace
                for (let i = ptr; i < content.length; i++) {
                    if (content[i] === '{') {
                        braceCount++;
                        foundStart = true;
                    } else if (content[i] === '}') {
                        braceCount--;
                        if (foundStart && braceCount === 0) {
                            closingIndex = i;
                            break;
                        }
                    }
                }

                if (closingIndex !== -1) {
                    const injection = `    ${tile.id}: { name: "${tile.name}", col: ${tile.col}, ren: ${tile.id} },\n`;
                    content = content.slice(0, closingIndex) + injection + content.slice(closingIndex);
                }
            }

            // 3. Append Render Function at the end
            const renderFunc = `\n// Custom Tile: ${tile.name}\nRenderRegistry.register(${tile.id}, (ctx, tx, ty, x, y, map, def) => {\n    ${tile.code}\n});\n`;
            content += renderFunc;
        });

        this.download(content, 'tile.js');
        document.getElementById('save-modal').style.display = 'none';
        // Clear list so we don't double add if clicked again? 
        // No, keep it in case user wants to save again. But maybe warn? 
        // For this simple editor, we assume user saves once or overwrites.
    },

    download(content, filename) {
        const blob = new Blob([content], { type: 'text/javascript' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
    }
};
